### PR TITLE
Adding bower and infrastructure

### PR DESCRIPTION
**Pull request by stulees**
- circle ci build file
- base tasks defined in gulp file, no testing as of yet
- package.json updated to add dev dependencies and rise vision as an author
- added bower file

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review. I've not added a gulp `build` task as of yet. I'm not going to do so unless I run into a situation of needing to modify source code at which point I will add several gulp tasks for compiling all necessary files. I had to add a `test` gulp task to appease circle ci. I will tag this new version after merging this PR. Thanks

**Comment by donnapep** [comment]
@stulees If there is no build, and no tests to run, then I don't think there's any point in having a `circle.yml` file and running it through CCI.

Also, I believe that we had decided to standardize on including an `rv-` prefix in front of the Bower and npm package names when forking a repo. Thx.

**Comment by stulees** [comment]
@donnapep It's not going to permanently have no build or tests to run, it's for now while I get through integration and work with it in Video Folder. I put in the time now to set up infrastructure instead of later. Not particularly wanting to undo it only to have to possibly do it again. 

We decided moving forward to not use the `rv-` prefix because it doesn't work with a `gulp bump`. Thanks

**Comment by donnapep** [comment]
@stulees OK re `circle.yml`.

Re: `rv-` prefix. That's when it was put on the `version` as a suffix. I'm talking about the `name` property like how [angular-bootstrap-colorpicker](https://github.com/Rise-Vision/angular-bootstrap-colorpicker) does it.

**Comment by stulees** [comment]
@donnapep Oh now I see, yes they should be prefixed. Have done so and rebased. Thanks

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
